on:
  issue_comment:
    types: [created]
name: Commented Pull Request
jobs:
  pullRequestHandler:
    name: PullRequestHandler
    runs-on: windows-latest
    steps:
      - name: Checkout
        # v 4.3.0, 2025-08-11
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: PullRequestHandler
        # 2025-09-19
        uses: ScoopInstaller/GithubActions@c92396e80eae6ef076cb65b4b53e8729688e03f5
        if: startsWith(github.event.comment.body, '/verify')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
